/***********************************************************************************************************************************
Command and Option Configuration

Automatically generated by Build.pm -- do not modify directly.
***********************************************************************************************************************************/

/***********************************************************************************************************************************
Command data
***********************************************************************************************************************************/
ConfigCommandData configCommandData[] = CONFIG_COMMAND_LIST
(
    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("archive-get")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("archive-push")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("backup")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("check")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("expire")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("help")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("info")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("local")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("remote")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("restore")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("stanza-create")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("stanza-upgrade")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("start")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("stop")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("version")
    )
)

/***********************************************************************************************************************************
Option data
***********************************************************************************************************************************/
ConfigOptionData configOptionData[] = CONFIG_OPTION_LIST
(
    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("archive-async")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptArchiveAsync)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("archive-check")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptArchiveCheck)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("archive-copy")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptArchiveCopy)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("archive-max-mb")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptArchiveMaxMb)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("archive-queue-max")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptArchiveQueueMax)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("archive-timeout")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptArchiveTimeout)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("backup-cmd")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptBackupCmd)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("backup-config")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptBackupConfig)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("backup-host")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptBackupHost)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("backup-ssh-port")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptBackupSshPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("backup-standby")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptBackupStandby)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("backup-user")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptBackupUser)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("buffer-size")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptBufferSize)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("checksum-page")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptChecksumPage)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("cmd-ssh")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptCmdSsh)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("command")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptCommand)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("compress")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptCompress)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("compress-level")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptCompressLevel)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("compress-level-network")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptCompressLevelNetwork)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("config")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptConfig)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db1-cmd")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbCmd)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db2-cmd")
        CONFIG_OPTION_INDEX(1)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbCmd)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db3-cmd")
        CONFIG_OPTION_INDEX(2)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbCmd)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db4-cmd")
        CONFIG_OPTION_INDEX(3)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbCmd)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db5-cmd")
        CONFIG_OPTION_INDEX(4)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbCmd)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db6-cmd")
        CONFIG_OPTION_INDEX(5)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbCmd)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db7-cmd")
        CONFIG_OPTION_INDEX(6)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbCmd)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db8-cmd")
        CONFIG_OPTION_INDEX(7)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbCmd)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db1-config")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbConfig)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db2-config")
        CONFIG_OPTION_INDEX(1)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbConfig)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db3-config")
        CONFIG_OPTION_INDEX(2)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbConfig)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db4-config")
        CONFIG_OPTION_INDEX(3)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbConfig)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db5-config")
        CONFIG_OPTION_INDEX(4)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbConfig)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db6-config")
        CONFIG_OPTION_INDEX(5)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbConfig)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db7-config")
        CONFIG_OPTION_INDEX(6)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbConfig)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db8-config")
        CONFIG_OPTION_INDEX(7)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbConfig)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db1-host")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbHost)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db2-host")
        CONFIG_OPTION_INDEX(1)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbHost)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db3-host")
        CONFIG_OPTION_INDEX(2)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbHost)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db4-host")
        CONFIG_OPTION_INDEX(3)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbHost)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db5-host")
        CONFIG_OPTION_INDEX(4)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbHost)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db6-host")
        CONFIG_OPTION_INDEX(5)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbHost)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db7-host")
        CONFIG_OPTION_INDEX(6)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbHost)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db8-host")
        CONFIG_OPTION_INDEX(7)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbHost)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db-include")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbInclude)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db1-path")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db2-path")
        CONFIG_OPTION_INDEX(1)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db3-path")
        CONFIG_OPTION_INDEX(2)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db4-path")
        CONFIG_OPTION_INDEX(3)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db5-path")
        CONFIG_OPTION_INDEX(4)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db6-path")
        CONFIG_OPTION_INDEX(5)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db7-path")
        CONFIG_OPTION_INDEX(6)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db8-path")
        CONFIG_OPTION_INDEX(7)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db1-port")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db2-port")
        CONFIG_OPTION_INDEX(1)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db3-port")
        CONFIG_OPTION_INDEX(2)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db4-port")
        CONFIG_OPTION_INDEX(3)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db5-port")
        CONFIG_OPTION_INDEX(4)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db6-port")
        CONFIG_OPTION_INDEX(5)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db7-port")
        CONFIG_OPTION_INDEX(6)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db8-port")
        CONFIG_OPTION_INDEX(7)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db1-socket-path")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbSocketPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db2-socket-path")
        CONFIG_OPTION_INDEX(1)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbSocketPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db3-socket-path")
        CONFIG_OPTION_INDEX(2)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbSocketPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db4-socket-path")
        CONFIG_OPTION_INDEX(3)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbSocketPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db5-socket-path")
        CONFIG_OPTION_INDEX(4)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbSocketPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db6-socket-path")
        CONFIG_OPTION_INDEX(5)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbSocketPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db7-socket-path")
        CONFIG_OPTION_INDEX(6)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbSocketPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db8-socket-path")
        CONFIG_OPTION_INDEX(7)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbSocketPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db1-ssh-port")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbSshPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db2-ssh-port")
        CONFIG_OPTION_INDEX(1)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbSshPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db3-ssh-port")
        CONFIG_OPTION_INDEX(2)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbSshPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db4-ssh-port")
        CONFIG_OPTION_INDEX(3)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbSshPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db5-ssh-port")
        CONFIG_OPTION_INDEX(4)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbSshPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db6-ssh-port")
        CONFIG_OPTION_INDEX(5)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbSshPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db7-ssh-port")
        CONFIG_OPTION_INDEX(6)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbSshPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db8-ssh-port")
        CONFIG_OPTION_INDEX(7)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbSshPort)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db-timeout")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbTimeout)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db1-user")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbUser)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db2-user")
        CONFIG_OPTION_INDEX(1)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbUser)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db3-user")
        CONFIG_OPTION_INDEX(2)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbUser)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db4-user")
        CONFIG_OPTION_INDEX(3)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbUser)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db5-user")
        CONFIG_OPTION_INDEX(4)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbUser)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db6-user")
        CONFIG_OPTION_INDEX(5)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbUser)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db7-user")
        CONFIG_OPTION_INDEX(6)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbUser)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db8-user")
        CONFIG_OPTION_INDEX(7)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDbUser)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("delta")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptDelta)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("force")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptForce)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("hardlink")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptHardlink)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("host-id")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptHostId)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("link-all")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptLinkAll)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("link-map")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptLinkMap)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("lock-path")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptLockPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("log-level-console")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptLogLevelConsole)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("log-level-file")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptLogLevelFile)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("log-level-stderr")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptLogLevelStderr)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("log-path")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptLogPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("log-timestamp")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptLogTimestamp)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("manifest-save-threshold")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptManifestSaveThreshold)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("neutral-umask")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptNeutralUmask)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("online")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptOnline)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("output")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptOutput)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("process")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptProcess)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("process-max")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptProcessMax)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("protocol-timeout")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptProtocolTimeout)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("recovery-option")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptRecoveryOption)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-cipher-key")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptRepoCipherKey)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-cipher-type")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptRepoCipherType)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-path")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptRepoPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-s3-bucket")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptRepoS3Bucket)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-s3-ca-file")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptRepoS3CaFile)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-s3-ca-path")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptRepoS3CaPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-s3-endpoint")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptRepoS3Endpoint)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-s3-host")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptRepoS3Host)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-s3-key")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptRepoS3Key)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-s3-key-secret")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptRepoS3KeySecret)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-s3-region")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptRepoS3Region)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-s3-verify-ssl")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptRepoS3VerifySsl)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-type")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptRepoType)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("resume")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptResume)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("retention-archive")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptRetentionArchive)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("retention-archive-type")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptRetentionArchiveType)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("retention-diff")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptRetentionDiff)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("retention-full")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptRetentionFull)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("set")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptSet)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("spool-path")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptSpoolPath)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("stanza")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptStanza)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("start-fast")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptStartFast)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("stop-auto")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptStopAuto)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("tablespace-map")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptTablespaceMap)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("tablespace-map-all")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptTablespaceMapAll)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("target")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptTarget)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("target-action")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptTargetAction)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("target-exclusive")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptTargetExclusive)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("target-timeline")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptTargetTimeline)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("test")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptTest)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("test-delay")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptTestDelay)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("test-point")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptTestPoint)
    )

    //------------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("type")
        CONFIG_OPTION_INDEX(0)
        CONFIG_OPTION_RULE_ID(cfgRuleOptType)
    )
)
