/***********************************************************************************************************************************
Command and Option Rules

Automatically generated by Build.pm -- do not modify directly.
***********************************************************************************************************************************/

/***********************************************************************************************************************************
Command rule data
***********************************************************************************************************************************/
CommandRule commandRule[] = CONFIG_COMMAND_LIST
(
    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("archive-get")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("archive-push")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("backup")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("check")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("expire")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("help")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("info")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("local")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("remote")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("restore")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("stanza-create")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("stanza-upgrade")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("start")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("stop")
    )

    CONFIG_COMMAND
    (
        CONFIG_COMMAND_NAME("version")
    )
)

/***********************************************************************************************************************************
Option rule data
***********************************************************************************************************************************/
OptionRule optionRule[] = CONFIG_OPTION_LIST
(
    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("archive-async")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeBoolean)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(true)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEFAULT("0")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("archive-check")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeBoolean)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(true)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND_LIST
            (
                cfgRuleOptOnline,
                "1"
            )

            CONFIG_OPTION_DEFAULT("1")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("archive-copy")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeBoolean)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(true)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEFAULT("0")

            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdBackup)

                CONFIG_OPTION_DEPEND_LIST
                (
                    cfgRuleOptArchiveCheck,
                    "1"
                )
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("archive-max-mb")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeInteger)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("archive-queue-max")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeInteger)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("archive-timeout")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeFloat)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_ALLOW_RANGE(0.1, 86400)
            CONFIG_OPTION_DEFAULT("60")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("backup-cmd")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND(cfgRuleOptBackupHost)
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("backup-config")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND(cfgRuleOptBackupHost)
            CONFIG_OPTION_DEFAULT("/etc/pgbackrest.conf")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("backup-host")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("backup-ssh-port")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeInteger)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND(cfgRuleOptBackupHost)
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("backup-standby")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeBoolean)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(true)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEFAULT("0")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("backup-user")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND(cfgRuleOptBackupHost)
            CONFIG_OPTION_DEFAULT("backrest")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("buffer-size")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeInteger)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_ALLOW_LIST
            (
                "16384",
                "32768",
                "65536",
                "131072",
                "262144",
                "524288",
                "1048576",
                "2097152",
                "4194304",
                "8388608",
                "16777216"
            )

            CONFIG_OPTION_DEFAULT("4194304")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("checksum-page")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeBoolean)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(true)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("cmd-ssh")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEFAULT("ssh")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("command")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionCommandLine)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("compress")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeBoolean)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(true)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEFAULT("1")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("compress-level")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeInteger)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_ALLOW_RANGE(0, 9)
            CONFIG_OPTION_DEFAULT("6")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("compress-level-network")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeInteger)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_ALLOW_RANGE(0, 9)
            CONFIG_OPTION_DEFAULT("3")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("config")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionCommandLine)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(true)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEFAULT("/etc/pgbackrest.conf")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db-cmd")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(8)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND(cfgRuleOptDbHost)
            CONFIG_OPTION_PREFIX("db")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db-config")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(8)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND(cfgRuleOptDbHost)
            CONFIG_OPTION_DEFAULT("/etc/pgbackrest.conf")
            CONFIG_OPTION_PREFIX("db")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db-host")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionStanza)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(8)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_PREFIX("db")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db-include")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeHash)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db-path")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionStanza)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(8)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_PREFIX("db")

            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdArchiveGet)

                CONFIG_OPTION_COMMAND_REQUIRED(false)

            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdArchivePush)

                CONFIG_OPTION_COMMAND_REQUIRED(false)

            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdLocal)

                CONFIG_OPTION_COMMAND_REQUIRED(false)

            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdRemote)

                CONFIG_OPTION_COMMAND_REQUIRED(false)
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db-port")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionStanza)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeInteger)

        CONFIG_OPTION_INDEX_TOTAL(8)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEFAULT("5432")
            CONFIG_OPTION_PREFIX("db")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db-socket-path")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionStanza)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(8)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_PREFIX("db")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db-ssh-port")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionStanza)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeInteger)

        CONFIG_OPTION_INDEX_TOTAL(8)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND(cfgRuleOptDbHost)
            CONFIG_OPTION_PREFIX("db")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db-timeout")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeFloat)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_ALLOW_RANGE(0.1, 604800)
            CONFIG_OPTION_DEFAULT("1800")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("db-user")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionStanza)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(8)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND(cfgRuleOptDbHost)
            CONFIG_OPTION_DEFAULT("postgres")
            CONFIG_OPTION_PREFIX("db")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("delta")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionCommandLine)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeBoolean)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdRestore)

                CONFIG_OPTION_DEFAULT("0")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("force")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionCommandLine)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeBoolean)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdBackup)

                CONFIG_OPTION_DEPEND_LIST
                (
                    cfgRuleOptOnline,
                    "0"
                )

                CONFIG_OPTION_DEFAULT("0")

            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdRestore)

                CONFIG_OPTION_DEFAULT("0")

            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdStanzaCreate)

                CONFIG_OPTION_DEFAULT("0")

            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdStop)

                CONFIG_OPTION_DEFAULT("0")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("hardlink")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeBoolean)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(true)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEFAULT("0")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("host-id")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionCommandLine)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeInteger)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("link-all")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeBoolean)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(true)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEFAULT("0")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("link-map")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeHash)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("lock-path")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEFAULT("/tmp/pgbackrest")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("log-level-console")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_ALLOW_LIST
            (
                "off",
                "error",
                "warn",
                "info",
                "detail",
                "debug",
                "trace"
            )

            CONFIG_OPTION_DEFAULT("warn")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("log-level-file")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_ALLOW_LIST
            (
                "off",
                "error",
                "warn",
                "info",
                "detail",
                "debug",
                "trace"
            )

            CONFIG_OPTION_DEFAULT("info")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("log-level-stderr")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_ALLOW_LIST
            (
                "off",
                "error",
                "warn",
                "info",
                "detail",
                "debug",
                "trace"
            )

            CONFIG_OPTION_DEFAULT("warn")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("log-path")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEFAULT("/var/log/pgbackrest")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("log-timestamp")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeBoolean)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(true)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEFAULT("1")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("manifest-save-threshold")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeInteger)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEFAULT("1073741824")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("neutral-umask")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeBoolean)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(true)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEFAULT("1")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("online")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionCommandLine)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeBoolean)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(true)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEFAULT("1")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("output")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionCommandLine)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdInfo)

                CONFIG_OPTION_ALLOW_LIST
                (
                    "text",
                    "json"
                )

                CONFIG_OPTION_DEFAULT("text")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("process")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionCommandLine)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeInteger)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdLocal)

                CONFIG_OPTION_COMMAND_REQUIRED(true)

            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdRemote)

                CONFIG_OPTION_COMMAND_REQUIRED(false)
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("process-max")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeInteger)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_ALLOW_RANGE(1, 96)
            CONFIG_OPTION_DEFAULT("1")
            CONFIG_OPTION_NAME_ALT("thread-max")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("protocol-timeout")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeFloat)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_ALLOW_RANGE(0.1, 604800)
            CONFIG_OPTION_DEFAULT("1830")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("recovery-option")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeHash)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND_LIST
            (
                cfgRuleOptType,
                "default",
                "name",
                "time",
                "xid"
            )
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-cipher-key")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(true)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND_LIST
            (
                cfgRuleOptRepoCipherType,
                "aes-256-cbc"
            )
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-cipher-type")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(true)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_ALLOW_LIST
            (
                "none",
                "aes-256-cbc"
            )

            CONFIG_OPTION_DEFAULT("none")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-path")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEFAULT("/var/lib/pgbackrest")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-s3-bucket")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND_LIST
            (
                cfgRuleOptRepoType,
                "s3"
            )
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-s3-ca-file")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND_LIST
            (
                cfgRuleOptRepoType,
                "s3"
            )
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-s3-ca-path")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND_LIST
            (
                cfgRuleOptRepoType,
                "s3"
            )
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-s3-endpoint")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND_LIST
            (
                cfgRuleOptRepoType,
                "s3"
            )
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-s3-host")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND_LIST
            (
                cfgRuleOptRepoType,
                "s3"
            )
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-s3-key")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(true)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND_LIST
            (
                cfgRuleOptRepoType,
                "s3"
            )
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-s3-key-secret")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(true)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND_LIST
            (
                cfgRuleOptRepoType,
                "s3"
            )
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-s3-region")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND_LIST
            (
                cfgRuleOptRepoType,
                "s3"
            )
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-s3-verify-ssl")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeBoolean)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(true)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND_LIST
            (
                cfgRuleOptRepoType,
                "s3"
            )

            CONFIG_OPTION_DEFAULT("1")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("repo-type")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_ALLOW_LIST
            (
                "cifs",
                "posix",
                "s3"
            )

            CONFIG_OPTION_DEFAULT("posix")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("resume")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeBoolean)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(true)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEFAULT("1")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("retention-archive")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeInteger)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_ALLOW_RANGE(1, 9999999)
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("retention-archive-type")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_ALLOW_LIST
            (
                "full",
                "diff",
                "incr"
            )

            CONFIG_OPTION_DEFAULT("full")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("retention-diff")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeInteger)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_ALLOW_RANGE(1, 9999999)
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("retention-full")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeInteger)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_ALLOW_RANGE(1, 9999999)
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("set")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionCommandLine)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdRestore)

                CONFIG_OPTION_DEFAULT("latest")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("spool-path")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND_LIST
            (
                cfgRuleOptArchiveAsync,
                "1"
            )

            CONFIG_OPTION_DEFAULT("/var/spool/pgbackrest")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("stanza")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionCommandLine)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchiveGet)
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdCheck)
            CONFIG_COMMAND_VALID(cfgRuleCmdExpire)
            CONFIG_COMMAND_VALID(cfgRuleCmdInfo)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaCreate)
            CONFIG_COMMAND_VALID(cfgRuleCmdStanzaUpgrade)
            CONFIG_COMMAND_VALID(cfgRuleCmdStart)
            CONFIG_COMMAND_VALID(cfgRuleCmdStop)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdInfo)

                CONFIG_OPTION_COMMAND_REQUIRED(false)

            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdRemote)

                CONFIG_OPTION_COMMAND_REQUIRED(false)

            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdStart)

                CONFIG_OPTION_COMMAND_REQUIRED(false)

            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdStop)

                CONFIG_OPTION_COMMAND_REQUIRED(false)
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("start-fast")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeBoolean)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(true)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEFAULT("0")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("stop-auto")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeBoolean)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(true)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEFAULT("0")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("tablespace-map")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeHash)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("tablespace-map-all")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionGlobal)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("target")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionCommandLine)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdRestore)

                CONFIG_OPTION_DEPEND_LIST
                (
                    cfgRuleOptType,
                    "name",
                    "time",
                    "xid"
                )
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("target-action")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionCommandLine)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdRestore)

                CONFIG_OPTION_ALLOW_LIST
                (
                    "pause",
                    "promote",
                    "shutdown"
                )

                CONFIG_OPTION_DEPEND_LIST
                (
                    cfgRuleOptType,
                    "name",
                    "time",
                    "xid"
                )

                CONFIG_OPTION_DEFAULT("pause")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("target-exclusive")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionCommandLine)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeBoolean)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdRestore)

                CONFIG_OPTION_DEPEND_LIST
                (
                    cfgRuleOptType,
                    "time",
                    "xid"
                )

                CONFIG_OPTION_DEFAULT("0")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("target-timeline")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionCommandLine)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdRestore)

                CONFIG_OPTION_DEPEND_LIST
                (
                    cfgRuleOptType,
                    "default",
                    "name",
                    "time",
                    "xid"
                )

                CONFIG_OPTION_COMMAND_REQUIRED(false)
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("test")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionCommandLine)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeBoolean)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEFAULT("0")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("test-delay")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionCommandLine)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeFloat)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND_LIST
            (
                cfgRuleOptTest,
                "1"
            )

            CONFIG_OPTION_DEFAULT("5")
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("test-point")
        CONFIG_OPTION_REQUIRED(false)
        CONFIG_OPTION_SECTION(cfgRuleSectionCommandLine)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeHash)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdArchivePush)
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_DEPEND_LIST
            (
                cfgRuleOptTest,
                "1"
            )
        )
    )

    // -----------------------------------------------------------------------------------------------------------------------------
    CONFIG_OPTION
    (
        CONFIG_OPTION_NAME("type")
        CONFIG_OPTION_REQUIRED(true)
        CONFIG_OPTION_SECTION(cfgRuleSectionCommandLine)
        CONFIG_OPTION_TYPE(cfgRuleOptDefTypeString)

        CONFIG_OPTION_INDEX_TOTAL(1)
        CONFIG_OPTION_NEGATE(false)
        CONFIG_OPTION_SECURE(false)

        CONFIG_COMMAND_VALID_LIST
        (
            CONFIG_COMMAND_VALID(cfgRuleCmdBackup)
            CONFIG_COMMAND_VALID(cfgRuleCmdLocal)
            CONFIG_COMMAND_VALID(cfgRuleCmdRemote)
            CONFIG_COMMAND_VALID(cfgRuleCmdRestore)
        )

        CONFIG_OPTION_DATA
        (
            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdBackup)

                CONFIG_OPTION_ALLOW_LIST
                (
                    "full",
                    "diff",
                    "incr"
                )

                CONFIG_OPTION_DEFAULT("incr")

            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdLocal)

                CONFIG_OPTION_ALLOW_LIST
                (
                    "db",
                    "backup"
                )

            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdRemote)

                CONFIG_OPTION_ALLOW_LIST
                (
                    "db",
                    "backup"
                )

            CONFIG_OPTION_COMMAND_DATA(cfgRuleCmdRestore)

                CONFIG_OPTION_ALLOW_LIST
                (
                    "name",
                    "time",
                    "xid",
                    "preserve",
                    "none",
                    "immediate",
                    "default"
                )

                CONFIG_OPTION_DEFAULT("default")
        )
    )
)
