/***********************************************************************************************************************************
Command and Option Rules

Automatically generated by Build.pm -- do not modify directly.
***********************************************************************************************************************************/
#ifndef CONFIG_RULE_AUTO_H
#define CONFIG_RULE_AUTO_H

/***********************************************************************************************************************************
Command rule enum
***********************************************************************************************************************************/
typedef enum
{
    cfgRuleCmdArchiveGet,
    cfgRuleCmdArchivePush,
    cfgRuleCmdBackup,
    cfgRuleCmdCheck,
    cfgRuleCmdExpire,
    cfgRuleCmdHelp,
    cfgRuleCmdInfo,
    cfgRuleCmdLocal,
    cfgRuleCmdRemote,
    cfgRuleCmdRestore,
    cfgRuleCmdStanzaCreate,
    cfgRuleCmdStanzaUpgrade,
    cfgRuleCmdStart,
    cfgRuleCmdStop,
    cfgRuleCmdVersion,
} ConfigRuleCommand;

/***********************************************************************************************************************************
Option type rule enum
***********************************************************************************************************************************/
typedef enum
{
    cfgRuleOptDefTypeBoolean,
    cfgRuleOptDefTypeFloat,
    cfgRuleOptDefTypeHash,
    cfgRuleOptDefTypeInteger,
    cfgRuleOptDefTypeString,
} ConfigRuleOptionType;

/***********************************************************************************************************************************
Option rule enum
***********************************************************************************************************************************/
typedef enum
{
    cfgRuleOptArchiveAsync,
    cfgRuleOptArchiveCheck,
    cfgRuleOptArchiveCopy,
    cfgRuleOptArchiveMaxMb,
    cfgRuleOptArchiveQueueMax,
    cfgRuleOptArchiveTimeout,
    cfgRuleOptBackupCmd,
    cfgRuleOptBackupConfig,
    cfgRuleOptBackupHost,
    cfgRuleOptBackupSshPort,
    cfgRuleOptBackupStandby,
    cfgRuleOptBackupUser,
    cfgRuleOptBufferSize,
    cfgRuleOptChecksumPage,
    cfgRuleOptCmdSsh,
    cfgRuleOptCommand,
    cfgRuleOptCompress,
    cfgRuleOptCompressLevel,
    cfgRuleOptCompressLevelNetwork,
    cfgRuleOptConfig,
    cfgRuleOptDbCmd,
    cfgRuleOptDbConfig,
    cfgRuleOptDbHost,
    cfgRuleOptDbInclude,
    cfgRuleOptDbPath,
    cfgRuleOptDbPort,
    cfgRuleOptDbSocketPath,
    cfgRuleOptDbSshPort,
    cfgRuleOptDbTimeout,
    cfgRuleOptDbUser,
    cfgRuleOptDelta,
    cfgRuleOptForce,
    cfgRuleOptHardlink,
    cfgRuleOptHostId,
    cfgRuleOptLinkAll,
    cfgRuleOptLinkMap,
    cfgRuleOptLockPath,
    cfgRuleOptLogLevelConsole,
    cfgRuleOptLogLevelFile,
    cfgRuleOptLogLevelStderr,
    cfgRuleOptLogPath,
    cfgRuleOptLogTimestamp,
    cfgRuleOptManifestSaveThreshold,
    cfgRuleOptNeutralUmask,
    cfgRuleOptOnline,
    cfgRuleOptOutput,
    cfgRuleOptProcess,
    cfgRuleOptProcessMax,
    cfgRuleOptProtocolTimeout,
    cfgRuleOptRecoveryOption,
    cfgRuleOptRepoPath,
    cfgRuleOptRepoS3Bucket,
    cfgRuleOptRepoS3CaFile,
    cfgRuleOptRepoS3CaPath,
    cfgRuleOptRepoS3Endpoint,
    cfgRuleOptRepoS3Host,
    cfgRuleOptRepoS3Key,
    cfgRuleOptRepoS3KeySecret,
    cfgRuleOptRepoS3Region,
    cfgRuleOptRepoS3VerifySsl,
    cfgRuleOptRepoType,
    cfgRuleOptResume,
    cfgRuleOptRetentionArchive,
    cfgRuleOptRetentionArchiveType,
    cfgRuleOptRetentionDiff,
    cfgRuleOptRetentionFull,
    cfgRuleOptSet,
    cfgRuleOptSpoolPath,
    cfgRuleOptStanza,
    cfgRuleOptStartFast,
    cfgRuleOptStopAuto,
    cfgRuleOptTablespaceMap,
    cfgRuleOptTablespaceMapAll,
    cfgRuleOptTarget,
    cfgRuleOptTargetAction,
    cfgRuleOptTargetExclusive,
    cfgRuleOptTargetTimeline,
    cfgRuleOptTest,
    cfgRuleOptTestDelay,
    cfgRuleOptTestPoint,
    cfgRuleOptType,
} ConfigRuleOption;

#endif
